allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': true
  '@swc/core': false
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
